name: PrisonCore
main: com.wolvencraft.prison.PrisonSuite
version: 2.1.0
description: Main dependency for all PrisonSuite plugins
author: bitWolfy
soft-depend: [WorldEdit]
commands:
  prison:
    description: PrisonSuite help page
  ps:
    description: PrisonSuite help page
permissions:
  prison.*:
    default: op
    children:
      prison.admin: true
  prison.select.*:
    default: op
    children:
      prison.select.wand: true
      prison.select.commands: true
  prison.admin:
    default: op
    children:
      prison.select.*: true
      prison.mine.*: true
      prison.cells.*: true
      prison.regions.*: true